-- 01 Create fact banking
CREATE VIEW fact_banking AS
SELECT
  substr(t.TRANSACTION_DATE,1,4) || '-' ||
  substr(t.TRANSACTION_DATE,5,2) || '-' ||
  substr(t.TRANSACTION_DATE,7,2) AS TXN_DATE,
  CAST(substr(t.TRANSACTION_DATE,1,4) AS INT) AS TXN_YEAR,
  CAST(substr(t.TRANSACTION_DATE,5,2) AS INT) AS TXN_MONTH,
  CAST(substr(t.TRANSACTION_DATE,7,2) AS INT) AS TXN_DAY,
  t.TRANSACTION_HOUR,
  t.TRANSACTION_ID,
  t.CUSTOMER_ID,
  b.BRANCH, b.CHANNEL, b.REGION,
  p.PROD_CODE, p.PRODUCT_LINE, p.PRODUCT_GROUP, p.PRODUCT_DIV,
  t.UNITS,
  t.AMOUNT
FROM transactions t
LEFT JOIN branch b   ON t.BRANCH = b.BRANCH
LEFT JOIN products p ON t.PROD_CODE = p.PROD_CODE;
